### ISSUE TITLE
Data Consistency while using massive data. 

### ISSUE THREAD

**Issue by vishnuvg1984** [htgc/fluent-plugin-azurestorage#10]
Hi , 
We encountering consistency issues when dealign with big data of 255 million and more. . Basically ours is  a Single Aggregator with 4 multiprocess plugin, running a total of 4 instances of Fluentd. We checked the following scenarios.

1: When inputted with 299 Million lines, 48Million lines got lost
2: When inputted with 295 Million lines, 33Million lines got lost

We tried to save the output to a file location using out_file plugin and the data is consistent. It implies that data loss happening when pushing to azure. ie when using "azure storage" instead of "out _file " data loss happening. 

Anyone can help on this issue. Do we need to consider any other measures too while  using this plugin?

**Comment by phstudy** [comment]
Could you provider your fluentd setting?

**Comment by vishnuvg1984** [comment]
Aggregator fluentd conf below. This is a single aggregator config file. Data is just a sample log of any format {message: "sample log message here"} . We created a input log with 255 million lines(we used unix shell to create multiple lines of same data). Its around 250GB size, so not poossible to share here. 

From the forwarder, we just read using tail plugin with a read rate of 5000 lines / sec and just forwarding to aggregator. 


<source>
 type secure_forward
 bind 0.0.0.0 # default
 port 24224 # default
 self_hostname hname
 shared_key    ThunderBolt
 secure yes
 ca_cert_path        /etc/pki/tls/certs/ca_cert.pem
 ca_private_key_path /etc/pki/tls/certs/ca_key.pem
 ca_private_key_passphrase D3w0FcdL80
 log_level trace
</source>




# Successfully parsed logs 
<match success>
type azurestorage
 azure_storage_account    storageaccount
 azure_storage_access_key key
 azure_container          logs
 azure_storage_type       blob
 store_as                 gzip
 auto_create_container    true
 path                     consistencycheck-FLT02/
 azure_object_key_format  %{path}DataCenterX_fwd02_%{time_slice}_%{index}.%{file_extension}
 time_slice_format        %Y%m%d-%H
 #time_slice_wait          10m
 format single_value

#buffering
 buffer_type file
 buffer_path /datadrive/buffer/td
 buffer_chunk_limit 16m
 buffer_queue_limit 16384
 retry_wait 1m
 num_threads 2
 log_level trace
 flush_interval 10s
</match>

**Comment by vishnuvg1984** [comment]
Hi ,
Some more input.   Increased the flush_interval to 1 minutes and confirmed the following 
1: While using single fluentd process, data is consistent. 
2: When spinning multiple fluentd processs using in_multiprocess plugin, data inconsistent. 
"http://docs.fluentd.org/v0.10/articles/in_multiprocess".

When checked with 19million 1 million lost while using 4 fluentd process simultaneously.

**Comment by vishnuvg1984** [comment]
Hi ,
Got the cause of the issue. When using multiple fluentd process,(using in_multiprocess), azure storage plugin overwrites the blob files from other process . I'd given 4 unique blob name for each process and the  data is consistent now. 
To clarify more : 
Input Data : 1757210 lines of log,
Test scenarios
1: Using 4 fluentd process to a single blob location, data inconsistent due to overwrite. Output log: 134210
2:  Using 4 fluentd process to a different blob locations, then the data is consistent as given below. 
Blob1- 440396
Blob2 - 440662
Blob3 - 435567
Blob4- 440585

It would be good, if the overwrite aware of the process context and decides to rewrite or not.

**Comment by phstudy** [comment]
In fact, this plugin does detect blob status and [avoid to override blob](https://github.com/htgc/fluent-plugin-azurestorage/blob/master/lib/fluent/plugin/out_azurestorage.rb#L116). But multiple threads may cause race condition and overridden uncommitted blob for file size > 64MB...

**Comment by vishnuvg1984** [comment]
Hi, 

Thanks I managed to solve the issue by passing a unique naming for multiple threads to the parameter " azure_object_key_format " . It solved the issue. Thanks a lot. Now the data is consistent.
