### ISSUE TITLE
Using log records in azure_object_key_format

### ISSUE THREAD

**Issue by caruccio** [htgc/fluent-plugin-azurestorage#17]
Hello there. Thanks for your work on this plugin. We just started using it at @GetupCloud.

Now for my question: How hard would it be to allow for `azure_object_key_format` use records from the log entry?

**Comment by toddysm** [comment]
Hi @caruccio, can you please provide more details what you mean with "use records from the log entry". Example will be helpful.

**Comment by caruccio** [comment]
Hi @toddysm. Sorry, I forgot to give an example:

Suppose I have this log record:

```json
{
  "docker": {
    "container_id": "6b079acd42a3660da51a5c70ceac114c42a129ccfb5a0a14b385774ca163e03a"
  },
  "kubernetes": {
    "namespace_name":"projectx",
    "pod_name":"api-23-wx6s5",
    "pod_id":"8d99b2f6-043d-11e7-a1aa-000d3ac067a6",
    "labels":{
      "deployment":"api-23",
      "deploymentconfig":"api",
      "name":"api"
    },
    "host":"infra-1.ldcg41toube3bstzmo4vrspsid.nx.internal.cloudapp.net",
    "namespace_id":"163a003b-f930-11e6-a684-000d3ac063b4",
    "container_name":"api"
  },
  "hostname":"infra-1.ldcg41toube3bstzmo4vrspsid.nx.internal.cloudapp.net",
  "message":"10.128.0.1 - - [10/Mar/2017:00:00:02 +0000] \"GET /health/ HTTP/1.1\" 200 2 \"-\" \"Go-http-client/1.1\"\n",
  "pipeline_metadata": {
    "collector": {
      "ipaddr4":"10.128.0.34",
      "ipaddr6":"fe80::d818:1bff:fe34:e2b8",
      "inputname":"fluent-plugin-in_tail",
      "name":"fluentd openshift",
      "received_at":"2017-03-10T00:00:02.721958726Z",
      "version":"0.12.29 1.4.0"
    }
  },
  "level":"3",
  "@timestamp":"2017-03-10T00:00:02.000000+00:00"
}
```

I'd like to b able to name my blob object key name using keys from this record, like this:

```
azure_object_key_format  %{path}%{kubernetes.namespace_id}/%{kubernetes.pod_name}/%{time_slice}_%{index}.%{file_extension}
```
Thanks for you reply.

**Comment by toddysm** [comment]
Hi @caruccio, unfortunately, I don't think this will be solvable using the approach you are proposing. Here are the problems I see right now:

1. The logic for creating the files that store the records encompasses the logic for formatting the records, which means the filename should not be dependent on the record content. Depending on how you configure Fluent, the same file may contain records from multiple pods and/or namespaces. What will happen if the same collector receives two records that have different pod_name and namespace_id?
2. If we are to implement this then we would like to make it generic so one can choose not specific JSON keys from the record but any key, which will make the logic for handling the files quite complex and may have impact on the performance as well as it can introduce some instability in the plugin

As a design principle, we think it is better to keep the plugin independent from the content and not make any decisions on what type of records (and their content) are passed through it.

Hope this makes sense.

**Comment by caruccio** [comment]
Hi @toddysm, thanks for your time explaining this. It make complete sense now that I understand it better.

**Comment by toddysm** [comment]
@caruccio, few suggestions:

- You may want to look at the record-modifier and the parser plugins and figure out a logic to tag the records before they reach the output plugin. You will still not be able to create dynamic outputs based on the data from the record but you may have a way to logically split the events into higher level buckets
- The best way to look at this, in my opinion, is to slice and dice the data in your reporting and visualization tool. I don't know what you use for visualization but most of the tools will have a capability to aggregate by any of the fields in the record. In this case it doesn't matter whether the data is split in different folders, files etc.
