### ISSUE TITLE
Plugin installation pulls in latest version of fluentd

### ISSUE THREAD

**Issue by raags** [htgc/fluent-plugin-azurestorage#9]
This can cause issues if an older version of fluentd is running, and break existing plugins. Can it be made a runtime dependency? The plugin can check for the version and fail at runtime. Considering that this is a plugin for fluentd, it ideally should not pull in fluentd it self as a dependency.

**Comment by toddysm** [comment]
Hi @raags, I understand this is an old issue but we need to address it before we decide on closing or pursuing it. 
So, `fluentd` is added as a runtime dependency in the gemspec and there is no `require` in the code for the it in the code. The library should not be pulling the latest `fluentd`. Would you be able to provide some repro steps or more details how to reproduce the problem?

**Comment by toddysm** [comment]
Closed as inactive. If the issue persists please provide repro steps.
